services:
  # 后端API服务
  - type: web
    name: ai-science-base-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.api_server:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ai-science-base-db
          property: connectionString

  # 前端服务
  - type: web
    name: ai-science-base-frontend
    env: node
    buildCommand: cd ../frontend && npm install && npm run build
    startCommand: cd ../frontend && npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: VITE_API_URL
        value: https://ai-science-base-api.onrender.com

databases:
  - name: ai-science-base-db
    plan: free 